title = "Jack 'Wax' Reynolds"
baseURL = "https://jackwax.github.io"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "Hey it's Me"
  description = "It's me, Jacky!"
  facebook = ""
  twitter = "https://twitter.com/jaccwax"
  instagram = ""
  youtube = ""
  github = "https://github.com/jackwax"
  linkedin = "https://www.linkedin.com/in/jackwax/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "images/toms.png"
  recent_posts_number = 2
